use plume_qe_core::versioning::{
    CIPHERTEXT_VERSION, ENCRYPTED_PAYLOAD_VERSION, KEM_CIPHERTEXT_VERSION, POLY_KEYPAIR_VERSION,
    POLY_PUBLIC_KEY_VERSION, POLY_SECRET_KEY_VERSION, WIRE_VERSION_MAJOR,
};

#[test]
fn wire_versions_match() {
    assert_eq!(POLY_PUBLIC_KEY_VERSION, WIRE_VERSION_MAJOR);
    assert_eq!(POLY_SECRET_KEY_VERSION, WIRE_VERSION_MAJOR);
    assert_eq!(POLY_KEYPAIR_VERSION, WIRE_VERSION_MAJOR);
    assert_eq!(CIPHERTEXT_VERSION, WIRE_VERSION_MAJOR);
    assert_eq!(KEM_CIPHERTEXT_VERSION, WIRE_VERSION_MAJOR);
    assert_eq!(ENCRYPTED_PAYLOAD_VERSION, WIRE_VERSION_MAJOR);
}
